spring.application.name=chatai
server.port=8085

gemini.api-url=https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent
gemini.api-key=YOUR_API_KEY

gateway.base-url=http://localhost:8080

inventory.service.url=http://localhost:0000/inventory/api
order.service.url=http://localhost:0000/order/api
internal.security.key=xxxxxxxxxxxxxxxx